apiVersion: v1
kind: Service
metadata:
  name: spark-thrift-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-thrift-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "spark-thrift-server.name" . }}
  ports:
    - name: thrift
      port: {{ .Values.service.thriftPort }}
      targetPort: {{ .Values.service.thriftPort }}
    - name: spark-ui
      port: {{ .Values.service.uiPort }}
      targetPort: {{ .Values.service.uiPort }}
